server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: core-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:govflow}?currentSchema=core_schema}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:postgres123}}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        default_schema: core_schema
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:govflow}
    password: ${RABBITMQ_PASSWORD:govflow123}

govflow:
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:govflow.events}
    queue-documentos-processados: ${RABBITMQ_QUEUE_DOCUMENTOS_PROCESSADOS:fila.documentos.processados}
    routing-key-documento-pronto: ${RABBITMQ_ROUTING_KEY_DOCUMENTO_PRONTO:documento.pronto.transferegov}
    routing-key-documento-rejeitado: ${RABBITMQ_ROUTING_KEY_DOCUMENTO_REJEITADO:documento.rejeitado}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    br.com.govflow.core: DEBUG
    org.hibernate.SQL: INFO
