server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: core-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:govflow}?currentSchema=core_schema}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:postgres}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:postgres123}}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        default_schema: core_schema
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: ${SPRING_JPA_SHOW_SQL:false}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    root: INFO
    br.com.govflow.core: DEBUG
    org.hibernate.SQL: INFO
