# Flyway Configuration for GovFlow
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true
flyway.baselineVersion=0
flyway.validateOnMigrate=true
flyway.schemas=whatsapp_schema,core_schema,transferegov_schema
flyway.defaultSchema=whatsapp_schema
flyway.table=flyway_schema_history
flyway.connectRetries=60
